# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e19a95c2604b5b467cf5418f05a3c15200821ffb029509deb61f74c9981f3257958b8db23e95b72b4cbf174a7de1ff2c8ae4d732c3a74b5d625de747b41f939d

test:
  secret_key_base: 7008f2080ca941cc2114490b578366ad76837008bd17cdb9e41a2bfbff966afe5ec1e4062e61d495327f1a8dce298a808a77f82ed1934aec9632238e42be1db6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
